# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b7fc7dec3b13c096ea2bf368060a0cae1f4bfcd858726fcb40e95ecadc0ead9de545db65f8268af9beeb58f2b5134f74082c62ade3e4b3d09e24a48f36a351a

test:
  secret_key_base: ee3729c34027eb3402eb8b67bff958135104ff738e507ed56a95972ef112c9e96d9d0087abaa090b1e6321fb4eff7e29db0e512d62b0b56c8f6ef429810a366b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
